# Generated by Django 3.2.6 on 2021-09-12 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images')),
                ('tag', models.CharField(max_length=250)),
                ('heading', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('desc', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('impost', models.ImageField(upload_to='Images')),
                ('available', models.BooleanField()),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cato')),
            ],
        ),
    ]
