# Generated by Django 3.2.6 on 2021-09-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='cate',
            new_name='cat',
        ),
    ]
