# Generated by Django 3.2.6 on 2021-09-12 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.date.today)),
                ('health', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('msg', models.TextField()),
            ],
        ),
    ]
